[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200
  force = true

[build]
 command = "npm run build"
 publish = "dist/amor/browser"
 functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
 for = "/.netlify/functions/*"
 [headers.values]
   Access-Control-Allow-Origin = "*"
   Access-Control-Allow-Methods = "GET, POST, OPTIONS"
   Access-Control-Allow-Headers = "Content-Type"

[build.environment]
  FAUNADB_SECRET = "fnAFlqySWtAAQgxz9uNHjgDxeXWN8rQ1WMpk03WB"

[context.production.environment]
  FAUNADB_SECRET = "fnAFlqySWtAAQgxz9uNHjgDxeXWN8rQ1WMpk03WB"