[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200
  force = true

[build]
 command = "npm run build"
 publish = "dist/amor/browser"
 functions = "functions-build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200